# NOTICE: Turning these off temporarily because I ran out of build minutes.
# Test locally buy running the commands under "run". I will do this for all PRs.

# name: Python
#
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#
# env:
#   CARGO_TERM_COLOR: always
#
# jobs:
#   build:
#
#     runs-on: ubuntu-latest
#
#     steps:
#     - uses: actions/checkout@v4
#     - name: Run tests
#       run: |
#           pip install -r requirements.txt
#           pytest
